--[[
	HOLLOW OATH - Rig / equipment builder  (generated by tools/gen_rig_builder.py - do not hand-edit)

	Put this ModuleScript in ReplicatedStorage (name it HO_RigBuilder). Import the Phase 4 FBX files
	(File -> Import 3D, Scale Unit = Stud, keep the file names) and move each imported Model into
	ServerStorage.HO_Assets (or pass the model in yourself). Textures: run
	require(game.ServerStorage.HO_CityBuilder).ApplyTextures() - it textures everything in HO_Assets.

	WHY THIS EXISTS: Roblox re-centres every imported MeshPart on its own bounding box, so the Blender
	origins are lost. The tables below store each mesh's centre relative to its body part / grip, so the
	functions here put every piece back exactly where it was modelled.

	  local Rig = require(game.ReplicatedStorage.HO_RigBuilder)

	  -- NPC rigs (R6 topology, Motor6Ds named like a normal R6 character -> the Phase 2 KeyframeSequences
	  -- HO_Anim_Golem_* / HO_Anim_Hollow_* play on them with Humanoid.Animator:LoadAnimation):
	  local golem  = Rig.BuildCharacter("HO_Char_EarthGolem", CFrame.new(0, 0, 0))   -- CFrame of the FEET
	  local hollow = Rig.BuildCharacter("HO_Char_Hollow", CFrame.new(10, 0, 0))

	  -- Armour on any R6 character (player or NPC):
	  Rig.EquipArmor(player.Character, "Samurai")     -- "Ashigaru" | "Samurai" | "Oathguard"
	  Rig.RemoveArmor(player.Character)

	  -- Katana as a Tool (Handle at the grip, Tool.Grip = identity: blade forward, edge down):
	  local tool = Rig.MakeWeaponTool("CrimsonOath")   -- IronKatana TemperedKatana AshfallSword CrimsonOath MoonlitEdge
	  tool.Parent = player.Backpack
	  Rig.AttachSheath(player.Character, "CrimsonOath")  -- scabbard on the left hip

	  -- Floating stone fists (welded beside the forearms; animate the welds' C0 for punches):
	  Rig.AttachStoneFists(character)

	Glow meshes (names containing "_Glow") are set to Material Neon so they glow without textures.
]]

local ServerStorage = game:GetService("ServerStorage")
local Rig = {}

-- mesh name -> body part + centre offset (Roblox studs, part-local / grip-local)
local RIGS = {
	HO_Armor_Ashigaru = {
		kind = "armour",
		meshes = {
			HO_Armor_Ashigaru_Helmet__Black_Lacquer = {
				offset = {0.0, 0.7, -0.0},
				part = "Head",
			},
			HO_Armor_Ashigaru_Helmet__Iron_Wrought = {
				offset = {0.0, 0.355, -0.0},
				part = "Head",
			},
			HO_Armor_Ashigaru_LeftArm__Black_Lacquer = {
				offset = {-0.085, 0.08, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Ashigaru_LeftArm__Cloth_Navy = {
				offset = {-0.65, 0.42, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Ashigaru_LeftArm__Iron_Wrought = {
				offset = {0.0, 0.07, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Ashigaru_LeftLeg__Black_Lacquer = {
				offset = {0.0, 0.0, -0.15},
				part = "Left Leg",
			},
			HO_Armor_Ashigaru_LeftLeg__Iron_Wrought = {
				offset = {0.0, -0.23, -0.54},
				part = "Left Leg",
			},
			HO_Armor_Ashigaru_RightArm__Black_Lacquer = {
				offset = {0.085, 0.08, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Ashigaru_RightArm__Cloth_Navy = {
				offset = {0.65, 0.42, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Ashigaru_RightArm__Iron_Wrought = {
				offset = {0.0, 0.07, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Ashigaru_RightLeg__Black_Lacquer = {
				offset = {0.0, 0.0, -0.15},
				part = "Right Leg",
			},
			HO_Armor_Ashigaru_RightLeg__Iron_Wrought = {
				offset = {0.0, -0.23, -0.54},
				part = "Right Leg",
			},
			HO_Armor_Ashigaru_Torso__Black_Lacquer = {
				offset = {0.0, -0.26, -0.034},
				part = "Torso",
			},
			HO_Armor_Ashigaru_Torso__Cloth_Navy = {
				offset = {0.0, -0.16, -0.73},
				part = "Torso",
			},
			HO_Armor_Ashigaru_Torso__Iron_Wrought = {
				offset = {0.0, 1.07, -0.09},
				part = "Torso",
			},
		},
	},
	HO_Armor_Oathguard = {
		kind = "armour",
		meshes = {
			HO_Armor_Oathguard_Helmet__Gold_Leaf = {
				offset = {0.0, 0.6, -0.7},
				part = "Head",
			},
			HO_Armor_Oathguard_Helmet__Navy_Lacquer = {
				offset = {0.0, 0.3, -0.0},
				part = "Head",
			},
			HO_Armor_Oathguard_LeftArm__Cloth_White = {
				offset = {-0.65, 0.42, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Oathguard_LeftArm__Gold_Leaf = {
				offset = {0.0, 0.07, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Oathguard_LeftArm__Navy_Lacquer = {
				offset = {-0.085, 0.08, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Oathguard_LeftLeg__Gold_Leaf = {
				offset = {0.0, -0.23, -0.54},
				part = "Left Leg",
			},
			HO_Armor_Oathguard_LeftLeg__Navy_Lacquer = {
				offset = {0.0, 0.0, -0.15},
				part = "Left Leg",
			},
			HO_Armor_Oathguard_RightArm__Cloth_White = {
				offset = {0.65, 0.42, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Oathguard_RightArm__Gold_Leaf = {
				offset = {0.0, 0.07, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Oathguard_RightArm__Navy_Lacquer = {
				offset = {0.085, 0.08, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Oathguard_RightLeg__Gold_Leaf = {
				offset = {0.0, -0.23, -0.54},
				part = "Right Leg",
			},
			HO_Armor_Oathguard_RightLeg__Navy_Lacquer = {
				offset = {0.0, 0.0, -0.15},
				part = "Right Leg",
			},
			HO_Armor_Oathguard_Torso__Cloth_White = {
				offset = {0.0, -0.16, -0.73},
				part = "Torso",
			},
			HO_Armor_Oathguard_Torso__Gold_Leaf = {
				offset = {0.0, 0.61, -0.09},
				part = "Torso",
			},
			HO_Armor_Oathguard_Torso__Navy_Lacquer = {
				offset = {0.0, -0.26, -0.079},
				part = "Torso",
			},
		},
	},
	HO_Armor_Samurai = {
		kind = "armour",
		meshes = {
			HO_Armor_Samurai_Helmet__Black_Lacquer = {
				offset = {0.0, 0.3, -0.0},
				part = "Head",
			},
			HO_Armor_Samurai_Helmet__Gold_Leaf = {
				offset = {0.0, 0.8524, -0.7298},
				part = "Head",
			},
			HO_Armor_Samurai_Helmet__Red_Lacquer = {
				offset = {0.0, 0.07, -0.0},
				part = "Head",
			},
			HO_Armor_Samurai_LeftArm__Black_Lacquer = {
				offset = {-0.075, -0.04, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Samurai_LeftArm__Cloth_Crimson = {
				offset = {-0.65, 0.42, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Samurai_LeftArm__Gold_Leaf = {
				offset = {0.0, 0.07, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Samurai_LeftArm__Red_Lacquer = {
				offset = {-0.085, 0.18, -0.0},
				part = "Left Arm",
			},
			HO_Armor_Samurai_LeftLeg__Black_Lacquer = {
				offset = {-0.005, -0.13, -0.15},
				part = "Left Leg",
			},
			HO_Armor_Samurai_LeftLeg__Gold_Leaf = {
				offset = {0.0, -0.23, -0.54},
				part = "Left Leg",
			},
			HO_Armor_Samurai_LeftLeg__Red_Lacquer = {
				offset = {0.0, 0.0, -0.54},
				part = "Left Leg",
			},
			HO_Armor_Samurai_RightArm__Black_Lacquer = {
				offset = {0.075, -0.04, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Samurai_RightArm__Cloth_Crimson = {
				offset = {0.65, 0.42, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Samurai_RightArm__Gold_Leaf = {
				offset = {0.0, 0.07, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Samurai_RightArm__Red_Lacquer = {
				offset = {0.085, 0.18, -0.0},
				part = "Right Arm",
			},
			HO_Armor_Samurai_RightLeg__Black_Lacquer = {
				offset = {0.005, -0.13, -0.15},
				part = "Right Leg",
			},
			HO_Armor_Samurai_RightLeg__Gold_Leaf = {
				offset = {0.0, -0.23, -0.54},
				part = "Right Leg",
			},
			HO_Armor_Samurai_RightLeg__Red_Lacquer = {
				offset = {0.0, 0.0, -0.54},
				part = "Right Leg",
			},
			HO_Armor_Samurai_Torso__Black_Lacquer = {
				offset = {0.0, -0.14, -0.037},
				part = "Torso",
			},
			HO_Armor_Samurai_Torso__Cloth_Crimson = {
				offset = {0.0, -0.16, -0.73},
				part = "Torso",
			},
			HO_Armor_Samurai_Torso__Gold_Leaf = {
				offset = {0.0, 0.7034, -0.11},
				part = "Torso",
			},
			HO_Armor_Samurai_Torso__Red_Lacquer = {
				offset = {0.0, -0.325, -0.034},
				part = "Torso",
			},
		},
	},
	HO_Char_EarthGolem = {
		kind = "character",
		meshes = {
			HO_Char_EarthGolem_Head = {
				offset = {-0.0006, -0.2733, -0.1232},
				part = "Head",
			},
			HO_Char_EarthGolem_Head_Glow = {
				offset = {0.0, 0.25, -1.2},
				part = "Head",
			},
			HO_Char_EarthGolem_LeftArm = {
				offset = {-0.2441, -0.2808, -0.0493},
				part = "Left Arm",
			},
			HO_Char_EarthGolem_LeftLeg = {
				offset = {-0.0074, -0.1951, -0.4379},
				part = "Left Leg",
			},
			HO_Char_EarthGolem_RightArm = {
				offset = {0.2346, -0.2685, 0.0428},
				part = "Right Arm",
			},
			HO_Char_EarthGolem_RightLeg = {
				offset = {-0.0037, -0.22, -0.4454},
				part = "Right Leg",
			},
			HO_Char_EarthGolem_Torso = {
				offset = {0.0121, -0.2085, -0.1824},
				part = "Torso",
			},
			HO_Char_EarthGolem_Torso_Glow = {
				offset = {0.0, -0.75, -1.085},
				part = "Torso",
			},
		},
		scale = 2.4,
	},
	HO_Char_Hollow = {
		kind = "character",
		meshes = {
			HO_Char_Hollow_Head = {
				offset = {0.0011, 0.2398, 0.1281},
				part = "Head",
			},
			HO_Char_Hollow_Head_Glow = {
				offset = {0.0, 0.1, -0.585},
				part = "Head",
			},
			HO_Char_Hollow_LeftArm = {
				offset = {-0.0125, -0.3025, -0.0745},
				part = "Left Arm",
			},
			HO_Char_Hollow_LeftArm_Glow = {
				offset = {-0.185, -0.1007, -0.2499},
				part = "Left Arm",
			},
			HO_Char_Hollow_LeftLeg = {
				offset = {-0.0117, 0.0269, -0.2428},
				part = "Left Leg",
			},
			HO_Char_Hollow_RightArm = {
				offset = {0.008, -0.3037, -0.0751},
				part = "Right Arm",
			},
			HO_Char_Hollow_RightArm_Glow = {
				offset = {0.185, -0.1007, -0.2499},
				part = "Right Arm",
			},
			HO_Char_Hollow_RightLeg = {
				offset = {0.01, 0.0468, -0.2524},
				part = "Right Leg",
			},
			HO_Char_Hollow_Torso = {
				offset = {-0.0166, -0.3319, 0.0807},
				part = "Torso",
			},
			HO_Char_Hollow_Torso_Glow = {
				offset = {0.0384, 0.2743, -0.387},
				part = "Torso",
			},
		},
		scale = 1.0,
	},
	HO_Hero_StoneFist_Left = {
		kind = "weapon",
		meshes = {
			HO_Hero_StoneFist_Left = {
				offset = {-0.1812, -0.0777, 0.8228},
			},
			HO_Hero_StoneFist_Left_Glow = {
				offset = {0.0126, 0.0104, 0.3752},
			},
		},
	},
	HO_Hero_StoneFist_Right = {
		kind = "weapon",
		meshes = {
			HO_Hero_StoneFist_Right = {
				offset = {0.1901, -0.0777, 0.8228},
			},
			HO_Hero_StoneFist_Right_Glow = {
				offset = {-0.0064, 0.0033, 0.4128},
			},
		},
	},
	HO_Weapon_AshfallSword = {
		kind = "weapon",
		meshes = {
			HO_Weapon_AshfallSword_Glow = {
				offset = {0.0, 0.032, -1.8262},
			},
			HO_Weapon_AshfallSword__Gold_Leaf = {
				offset = {0.0, 0.0, -0.645},
			},
			HO_Weapon_AshfallSword__Iron_Wrought = {
				offset = {0.0, 0.0, -0.01},
			},
			HO_Weapon_AshfallSword__Steel_Dark = {
				offset = {0.0, 0.0142, -1.995},
			},
			HO_Weapon_AshfallSword__Tsuka_Wrap = {
				offset = {0.0, 0.005, -0.0},
			},
		},
	},
	HO_Weapon_AshfallSword_Saya = {
		kind = "weapon",
		meshes = {
			HO_Weapon_AshfallSword_Saya__Black_Lacquer = {
				offset = {0.0, 0.0108, -1.973},
			},
			HO_Weapon_AshfallSword_Saya__Cloth_Crimson = {
				offset = {0.1615, -0.194, -1.4715},
			},
			HO_Weapon_AshfallSword_Saya__Iron_Wrought = {
				offset = {0.0, 0.0, -2.033},
			},
		},
	},
	HO_Weapon_CrimsonOath = {
		kind = "weapon",
		meshes = {
			HO_Weapon_CrimsonOath_Glow = {
				offset = {0.0, 0.0632, -1.945},
			},
			HO_Weapon_CrimsonOath__Gold_Leaf = {
				offset = {0.0, 0.0, -0.035},
			},
			HO_Weapon_CrimsonOath__Steel_Blade = {
				offset = {0.0, 0.0743, -1.945},
			},
			HO_Weapon_CrimsonOath__Tsuka_Wrap = {
				offset = {0.0, 0.005, -0.0},
			},
		},
	},
	HO_Weapon_CrimsonOath_Saya = {
		kind = "weapon",
		meshes = {
			HO_Weapon_CrimsonOath_Saya__Gold_Leaf = {
				offset = {0.0449, -0.1282, -1.9845},
			},
			HO_Weapon_CrimsonOath_Saya__Red_Lacquer = {
				offset = {0.0, 0.0685, -1.9245},
			},
		},
	},
	HO_Weapon_IronKatana = {
		kind = "weapon",
		meshes = {
			HO_Weapon_IronKatana__Gold_Leaf = {
				offset = {0.0, 0.0, -0.615},
			},
			HO_Weapon_IronKatana__Iron_Wrought = {
				offset = {0.0, 0.0, 0.005},
			},
			HO_Weapon_IronKatana__Steel_Blade = {
				offset = {0.0, 0.0457, -1.845},
			},
			HO_Weapon_IronKatana__Tsuka_Wrap = {
				offset = {0.0, 0.005, -0.0},
			},
		},
	},
	HO_Weapon_IronKatana_Saya = {
		kind = "weapon",
		meshes = {
			HO_Weapon_IronKatana_Saya__Black_Lacquer = {
				offset = {0.0, 0.0417, -1.8275},
			},
			HO_Weapon_IronKatana_Saya__Cloth_Crimson = {
				offset = {0.1615, -0.1933, -1.4355},
			},
			HO_Weapon_IronKatana_Saya__Iron_Wrought = {
				offset = {0.0, 0.0145, -1.8875},
			},
		},
	},
	HO_Weapon_MoonlitEdge = {
		kind = "weapon",
		meshes = {
			HO_Weapon_MoonlitEdge_Glow = {
				offset = {0.0, 0.0497, -1.945},
			},
			HO_Weapon_MoonlitEdge__Gold_Leaf = {
				offset = {0.0, 0.0, -0.615},
			},
			HO_Weapon_MoonlitEdge__Iron_Wrought = {
				offset = {0.0, 0.0, -0.001},
			},
			HO_Weapon_MoonlitEdge__Steel_Blade = {
				offset = {0.0, 0.0607, -1.945},
			},
			HO_Weapon_MoonlitEdge__Tsuka_Wrap = {
				offset = {0.0, 0.005, -0.0},
			},
		},
	},
	HO_Weapon_MoonlitEdge_Saya = {
		kind = "weapon",
		meshes = {
			HO_Weapon_MoonlitEdge_Saya__Cloth_Crimson = {
				offset = {0.1615, -0.1928, -1.4595},
			},
			HO_Weapon_MoonlitEdge_Saya__Iron_Wrought = {
				offset = {0.0, 0.0286, -1.9845},
			},
			HO_Weapon_MoonlitEdge_Saya__Navy_Lacquer = {
				offset = {0.0, 0.0558, -1.9245},
			},
		},
	},
	HO_Weapon_TemperedKatana = {
		kind = "weapon",
		meshes = {
			HO_Weapon_TemperedKatana__Gold_Leaf = {
				offset = {0.0, 0.0, -0.035},
			},
			HO_Weapon_TemperedKatana__Iron_Wrought = {
				offset = {0.0, 0.0, -0.545},
			},
			HO_Weapon_TemperedKatana__Steel_Blade = {
				offset = {0.0, 0.065, -1.895},
			},
			HO_Weapon_TemperedKatana__Tsuka_Wrap = {
				offset = {0.0, 0.005, -0.0},
			},
		},
	},
	HO_Weapon_TemperedKatana_Saya = {
		kind = "weapon",
		meshes = {
			HO_Weapon_TemperedKatana_Saya__Black_Lacquer = {
				offset = {0.0, 0.0598, -1.876},
			},
			HO_Weapon_TemperedKatana_Saya__Cloth_Crimson = {
				offset = {0.1615, -0.1927, -1.4475},
			},
			HO_Weapon_TemperedKatana_Saya__Gold_Leaf = {
				offset = {0.0, 0.0302, -1.936},
			},
		},
	},
}

-- classic R6 joint frames (scale 1); translations are multiplied by the rig scale
local R6_JOINTS = {
	{"RootJoint", "HumanoidRootPart", "Torso", CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0), CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0)},
	{"Neck", "Torso", "Head", CFrame.new(0, 1, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0), CFrame.new(0, -0.5, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0)},
	{"Right Shoulder", "Torso", "Right Arm", CFrame.new(1, 0.5, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0), CFrame.new(-0.5, 0.5, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0)},
	{"Left Shoulder", "Torso", "Left Arm", CFrame.new(-1, 0.5, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0), CFrame.new(0.5, 0.5, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0)},
	{"Right Hip", "Torso", "Right Leg", CFrame.new(1, -1, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0), CFrame.new(0.5, 1, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0)},
	{"Left Hip", "Torso", "Left Leg", CFrame.new(-1, -1, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0), CFrame.new(-0.5, 1, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0)},
}
local R6_PARTS = {  -- size, rest centre relative to the HumanoidRootPart (scale 1)
	HumanoidRootPart = {Vector3.new(2, 2, 1), Vector3.new(0, 0, 0)},
	Torso = {Vector3.new(2, 2, 1), Vector3.new(0, 0, 0)},
	Head = {Vector3.new(2, 1, 1), Vector3.new(0, 1.5, 0)},
	["Right Arm"] = {Vector3.new(1, 2, 1), Vector3.new(1.5, 0, 0)},
	["Left Arm"] = {Vector3.new(1, 2, 1), Vector3.new(-1.5, 0, 0)},
	["Right Leg"] = {Vector3.new(1, 2, 1), Vector3.new(0.5, -2, 0)},
	["Left Leg"] = {Vector3.new(1, 2, 1), Vector3.new(-0.5, -2, 0)},
}

local function scaled(cf, s)
	return CFrame.new(cf.Position * s) * cf.Rotation
end

local function findAsset(name, given)
	if given then return given end
	local lib = ServerStorage:FindFirstChild("HO_Assets")
	local m = lib and lib:FindFirstChild(name, true)
	assert(m, "HO_RigBuilder: import " .. name .. ".fbx into ServerStorage.HO_Assets (or pass the model)")
	return m
end

-- all MeshParts of an imported asset, keyed by name
local function meshes(model)
	local out = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("MeshPart") then out[d.Name] = d end
	end
	if model:IsA("MeshPart") then out[model.Name] = model end
	return out
end

local function prep(mp)
	mp.Anchored = false
	mp.CanCollide = false
	mp.CanQuery = false
	mp.CanTouch = false
	mp.Massless = true
	if string.find(mp.Name, "_Glow") then
		mp.Material = Enum.Material.Neon
		local sa = mp:FindFirstChildOfClass("SurfaceAppearance")
		if sa then sa:Destroy() end
	end
end

local function weld(part0, mp, c0)
	mp.CFrame = part0.CFrame * c0
	local w = Instance.new("Weld")
	w.Name = "HO_Weld_" .. mp.Name
	w.Part0 = part0
	w.Part1 = mp
	w.C0 = c0
	w.Parent = mp
	return w
end

local function v3(t) return Vector3.new(t[1], t[2], t[3]) end

-- Build an animatable R6-topology NPC from an imported character asset. feetCFrame = where its feet stand.
function Rig.BuildCharacter(assetName, feetCFrame, assetModel)
	local data = assert(RIGS[assetName], "unknown rig " .. tostring(assetName))
	assert(data.kind == "character", assetName .. " is not a character rig")
	local s = data.scale
	local src = meshes(findAsset(assetName, assetModel))
	feetCFrame = feetCFrame or CFrame.new()

	local model = Instance.new("Model")
	model.Name = string.gsub(assetName, "^HO_Char_", "")
	local parts = {}
	local hrpCF = feetCFrame * CFrame.new(0, 3 * s, 0)
	for name, def in pairs(R6_PARTS) do
		local p = Instance.new("Part")
		p.Name = name
		p.Size = def[1] * s
		p.CFrame = hrpCF * CFrame.new(def[2] * s)
		p.Transparency = 1
		p.CanCollide = (name == "Torso" or name == "Head")
		p.Massless = (name ~= "HumanoidRootPart" and name ~= "Torso")
		p.Parent = model
		parts[name] = p
	end
	parts.HumanoidRootPart.CanCollide = false
	for _, j in ipairs(R6_JOINTS) do
		local m = Instance.new("Motor6D")
		m.Name = j[1]
		m.Part0 = parts[j[2]]
		m.Part1 = parts[j[3]]
		m.C0 = scaled(j[4], s)
		m.C1 = scaled(j[5], s)
		m.Parent = (j[2] == "HumanoidRootPart") and parts.HumanoidRootPart or parts.Torso
	end
	local visual = Instance.new("Folder")
	visual.Name = "Visual"
	visual.Parent = model
	for meshName, info in pairs(data.meshes) do
		local src_mp = src[meshName]
		if src_mp then
			local mp = src_mp:Clone()
			prep(mp)
			mp.Parent = visual
			weld(parts[info.part], mp, CFrame.new(v3(info.offset)))
		else
			warn("HO_RigBuilder: mesh missing from import:", meshName)
		end
	end
	local hum = Instance.new("Humanoid")
	hum.RigType = Enum.HumanoidRigType.R6
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	Instance.new("Animator").Parent = hum
	hum.Parent = model
	model.PrimaryPart = parts.HumanoidRootPart
	model.Parent = workspace
	return model
end

-- Weld an armour set onto an R6 character. Pieces are tagged so RemoveArmor can take them off again.
function Rig.EquipArmor(character, setName, assetModel)
	local assetName = "HO_Armor_" .. setName
	local data = assert(RIGS[assetName], "unknown armour set " .. tostring(setName))
	Rig.RemoveArmor(character)
	local src = meshes(findAsset(assetName, assetModel))
	local folder = Instance.new("Folder")
	folder.Name = "HO_Armor"
	folder:SetAttribute("Set", setName)
	for meshName, info in pairs(data.meshes) do
		local part = character:FindFirstChild(info.part)
		if src[meshName] and part then
			local mp = src[meshName]:Clone()
			prep(mp)
			mp.Parent = folder
			weld(part, mp, CFrame.new(v3(info.offset)))
		end
	end
	folder.Parent = character
	return folder
end

function Rig.RemoveArmor(character)
	local f = character:FindFirstChild("HO_Armor")
	if f then f:Destroy() end
end

-- welds every mesh of a weapon-type asset to `part0` with the extra frame `frame` (grip / fist centre)
local function attach(assetName, part0, frame, parent, assetModel)
	local data = assert(RIGS[assetName], "unknown asset " .. tostring(assetName))
	local src = meshes(findAsset(assetName, assetModel))
	for meshName, info in pairs(data.meshes) do
		if src[meshName] then
			local mp = src[meshName]:Clone()
			prep(mp)
			mp.Parent = parent
			weld(part0, mp, frame * CFrame.new(v3(info.offset)))
		end
	end
end

-- Tool with an invisible Handle at the grip centre. Tool.Grip = identity -> blade forward, edge down.
function Rig.MakeWeaponTool(weaponName, assetModel)
	local tool = Instance.new("Tool")
	tool.Name = weaponName
	tool.RequiresHandle = true
	tool.CanBeDropped = false
	local h = Instance.new("Part")
	h.Name = "Handle"
	h.Size = Vector3.new(0.2, 0.25, 0.9)
	h.Transparency = 1
	h.CanCollide = false
	h.Massless = true
	h.Parent = tool
	attach("HO_Weapon_" .. weaponName, h, CFrame.new(), tool, assetModel)
	return tool
end

-- Scabbard on the left hip (grip forward-up, tip back-down). Tweak SHEATH_C0 to taste.
Rig.SHEATH_C0 = CFrame.new(-1.15, -0.75, -0.9) * CFrame.Angles(math.rad(25), math.pi, 0)
function Rig.AttachSheath(character, weaponName, assetModel)
	local old = character:FindFirstChild("HO_Sheath")
	if old then old:Destroy() end
	local f = Instance.new("Folder")
	f.Name = "HO_Sheath"
	attach("HO_Weapon_" .. weaponName .. "_Saya", character.Torso, Rig.SHEATH_C0, f, assetModel)
	f.Parent = character
	return f
end

-- Floating stone fists beside the forearms, punching forward. Returns {Right = {welds}, Left = {welds}}.
Rig.FIST_C0 = {Right = CFrame.new(1.6, -0.9, -0.9), Left = CFrame.new(-1.6, -0.9, -0.9)}
function Rig.AttachStoneFists(character)
	local old = character:FindFirstChild("HO_StoneFists")
	if old then old:Destroy() end
	local f = Instance.new("Folder")
	f.Name = "HO_StoneFists"
	local welds = {}
	for _, side in ipairs({"Right", "Left"}) do
		local sub = Instance.new("Folder")
		sub.Name = side
		sub.Parent = f
		attach("HO_Hero_StoneFist_" .. side, character[side .. " Arm"], Rig.FIST_C0[side], sub)
		welds[side] = {}
		for _, d in ipairs(sub:GetDescendants()) do
			if d:IsA("Weld") then table.insert(welds[side], d) end
		end
	end
	f.Parent = character
	return welds
end

Rig.RIGS = RIGS
return Rig
