--[[
	HOLLOW OATH - Rig / equipment builder  (generated by tools/gen_rig_builder.py - do not hand-edit)

	Put this ModuleScript in ReplicatedStorage (name it HO_RigBuilder). Import the Phase 4 FBX files
	(File -> Import 3D, Scale Unit = Stud, keep the file names) and move each imported Model into
	ServerStorage.HO_Assets (or pass the model in yourself). Textures: run
	require(game.ServerStorage.HO_CityBuilder).ApplyTextures() - it textures everything in HO_Assets.

	WHY THIS EXISTS: Roblox re-centres every imported MeshPart on its own bounding box, so the Blender
	origins are lost. The tables below store each mesh's centre relative to its body part / grip, so the
	functions here put every piece back exactly where it was modelled.

	  local Rig = require(game.ReplicatedStorage.HO_RigBuilder)

	  -- NPC rigs (R6 topology, Motor6Ds named like a normal R6 character -> the Phase 2 KeyframeSequences
	  -- HO_Anim_Golem_* / HO_Anim_Hollow_* play on them with Humanoid.Animator:LoadAnimation):
	  local golem  = Rig.BuildCharacter("HO_Char_EarthGolem", CFrame.new(0, 0, 0))   -- CFrame of the FEET
	  local hollow = Rig.BuildCharacter("HO_Char_Hollow", CFrame.new(10, 0, 0))

	  -- Armour on any R6 character (player or NPC):
	  Rig.EquipArmor(player.Character, "Samurai")     -- "Ashigaru" | "Samurai" | "Oathguard"
	  Rig.RemoveArmor(player.Character)

	  -- Katana as a Tool (Handle at the grip, Tool.Grip = identity: blade forward, edge down):
	  local tool = Rig.MakeWeaponTool("CrimsonOath")   -- IronKatana TemperedKatana AshfallSword CrimsonOath MoonlitEdge
	  tool.Parent = player.Backpack
	  Rig.AttachSheath(player.Character, "CrimsonOath")  -- scabbard on the left hip

	  -- Floating stone fists (welded beside the forearms; animate the welds' C0 for punches):
	  Rig.AttachStoneFists(character)

	Glow meshes (names containing "_Glow") are set to Material Neon so they glow without textures.
]]

local ServerStorage = game:GetService("ServerStorage")
local Rig = {}

--[[RIGS]]

-- classic R6 joint frames (scale 1); translations are multiplied by the rig scale
local R6_JOINTS = {
	{"RootJoint", "HumanoidRootPart", "Torso", CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0), CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0)},
	{"Neck", "Torso", "Head", CFrame.new(0, 1, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0), CFrame.new(0, -0.5, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0)},
	{"Right Shoulder", "Torso", "Right Arm", CFrame.new(1, 0.5, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0), CFrame.new(-0.5, 0.5, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0)},
	{"Left Shoulder", "Torso", "Left Arm", CFrame.new(-1, 0.5, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0), CFrame.new(0.5, 0.5, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0)},
	{"Right Hip", "Torso", "Right Leg", CFrame.new(1, -1, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0), CFrame.new(0.5, 1, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0)},
	{"Left Hip", "Torso", "Left Leg", CFrame.new(-1, -1, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0), CFrame.new(-0.5, 1, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0)},
}
local R6_PARTS = {  -- size, rest centre relative to the HumanoidRootPart (scale 1)
	HumanoidRootPart = {Vector3.new(2, 2, 1), Vector3.new(0, 0, 0)},
	Torso = {Vector3.new(2, 2, 1), Vector3.new(0, 0, 0)},
	Head = {Vector3.new(2, 1, 1), Vector3.new(0, 1.5, 0)},
	["Right Arm"] = {Vector3.new(1, 2, 1), Vector3.new(1.5, 0, 0)},
	["Left Arm"] = {Vector3.new(1, 2, 1), Vector3.new(-1.5, 0, 0)},
	["Right Leg"] = {Vector3.new(1, 2, 1), Vector3.new(0.5, -2, 0)},
	["Left Leg"] = {Vector3.new(1, 2, 1), Vector3.new(-0.5, -2, 0)},
}

local function scaled(cf, s)
	return CFrame.new(cf.Position * s) * cf.Rotation
end

local function findAsset(name, given)
	if given then return given end
	local lib = ServerStorage:FindFirstChild("HO_Assets")
	local m = lib and lib:FindFirstChild(name, true)
	assert(m, "HO_RigBuilder: import " .. name .. ".fbx into ServerStorage.HO_Assets (or pass the model)")
	return m
end

-- all MeshParts of an imported asset, keyed by name
local function meshes(model)
	local out = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("MeshPart") then out[d.Name] = d end
	end
	if model:IsA("MeshPart") then out[model.Name] = model end
	return out
end

local function prep(mp)
	mp.Anchored = false
	mp.CanCollide = false
	mp.CanQuery = false
	mp.CanTouch = false
	mp.Massless = true
	if string.find(mp.Name, "_Glow") then
		mp.Material = Enum.Material.Neon
		local sa = mp:FindFirstChildOfClass("SurfaceAppearance")
		if sa then sa:Destroy() end
	end
end

local function weld(part0, mp, c0)
	mp.CFrame = part0.CFrame * c0
	local w = Instance.new("Weld")
	w.Name = "HO_Weld_" .. mp.Name
	w.Part0 = part0
	w.Part1 = mp
	w.C0 = c0
	w.Parent = mp
	return w
end

local function v3(t) return Vector3.new(t[1], t[2], t[3]) end

-- Build an animatable R6-topology NPC from an imported character asset. feetCFrame = where its feet stand.
function Rig.BuildCharacter(assetName, feetCFrame, assetModel)
	local data = assert(RIGS[assetName], "unknown rig " .. tostring(assetName))
	assert(data.kind == "character", assetName .. " is not a character rig")
	local s = data.scale
	local src = meshes(findAsset(assetName, assetModel))
	feetCFrame = feetCFrame or CFrame.new()

	local model = Instance.new("Model")
	model.Name = string.gsub(assetName, "^HO_Char_", "")
	local parts = {}
	local hrpCF = feetCFrame * CFrame.new(0, 3 * s, 0)
	for name, def in pairs(R6_PARTS) do
		local p = Instance.new("Part")
		p.Name = name
		p.Size = def[1] * s
		p.CFrame = hrpCF * CFrame.new(def[2] * s)
		p.Transparency = 1
		p.CanCollide = (name == "Torso" or name == "Head")
		p.Massless = (name ~= "HumanoidRootPart" and name ~= "Torso")
		p.Parent = model
		parts[name] = p
	end
	parts.HumanoidRootPart.CanCollide = false
	for _, j in ipairs(R6_JOINTS) do
		local m = Instance.new("Motor6D")
		m.Name = j[1]
		m.Part0 = parts[j[2]]
		m.Part1 = parts[j[3]]
		m.C0 = scaled(j[4], s)
		m.C1 = scaled(j[5], s)
		m.Parent = (j[2] == "HumanoidRootPart") and parts.HumanoidRootPart or parts.Torso
	end
	local visual = Instance.new("Folder")
	visual.Name = "Visual"
	visual.Parent = model
	for meshName, info in pairs(data.meshes) do
		local src_mp = src[meshName]
		if src_mp then
			local mp = src_mp:Clone()
			prep(mp)
			mp.Parent = visual
			weld(parts[info.part], mp, CFrame.new(v3(info.offset)))
		else
			warn("HO_RigBuilder: mesh missing from import:", meshName)
		end
	end
	local hum = Instance.new("Humanoid")
	hum.RigType = Enum.HumanoidRigType.R6
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	Instance.new("Animator").Parent = hum
	hum.Parent = model
	model.PrimaryPart = parts.HumanoidRootPart
	model.Parent = workspace
	return model
end

-- Weld an armour set onto an R6 character. Pieces are tagged so RemoveArmor can take them off again.
function Rig.EquipArmor(character, setName, assetModel)
	local assetName = "HO_Armor_" .. setName
	local data = assert(RIGS[assetName], "unknown armour set " .. tostring(setName))
	Rig.RemoveArmor(character)
	local src = meshes(findAsset(assetName, assetModel))
	local folder = Instance.new("Folder")
	folder.Name = "HO_Armor"
	folder:SetAttribute("Set", setName)
	for meshName, info in pairs(data.meshes) do
		local part = character:FindFirstChild(info.part)
		if src[meshName] and part then
			local mp = src[meshName]:Clone()
			prep(mp)
			mp.Parent = folder
			weld(part, mp, CFrame.new(v3(info.offset)))
		end
	end
	folder.Parent = character
	return folder
end

function Rig.RemoveArmor(character)
	local f = character:FindFirstChild("HO_Armor")
	if f then f:Destroy() end
end

-- welds every mesh of a weapon-type asset to `part0` with the extra frame `frame` (grip / fist centre)
local function attach(assetName, part0, frame, parent, assetModel)
	local data = assert(RIGS[assetName], "unknown asset " .. tostring(assetName))
	local src = meshes(findAsset(assetName, assetModel))
	for meshName, info in pairs(data.meshes) do
		if src[meshName] then
			local mp = src[meshName]:Clone()
			prep(mp)
			mp.Parent = parent
			weld(part0, mp, frame * CFrame.new(v3(info.offset)))
		end
	end
end

-- Tool with an invisible Handle at the grip centre. Tool.Grip = identity -> blade forward, edge down.
function Rig.MakeWeaponTool(weaponName, assetModel)
	local tool = Instance.new("Tool")
	tool.Name = weaponName
	tool.RequiresHandle = true
	tool.CanBeDropped = false
	local h = Instance.new("Part")
	h.Name = "Handle"
	h.Size = Vector3.new(0.2, 0.25, 0.9)
	h.Transparency = 1
	h.CanCollide = false
	h.Massless = true
	h.Parent = tool
	attach("HO_Weapon_" .. weaponName, h, CFrame.new(), tool, assetModel)
	return tool
end

-- Scabbard on the left hip (grip forward-up, tip back-down). Tweak SHEATH_C0 to taste.
Rig.SHEATH_C0 = CFrame.new(-1.15, -0.75, -0.9) * CFrame.Angles(math.rad(25), math.pi, 0)
function Rig.AttachSheath(character, weaponName, assetModel)
	local old = character:FindFirstChild("HO_Sheath")
	if old then old:Destroy() end
	local f = Instance.new("Folder")
	f.Name = "HO_Sheath"
	attach("HO_Weapon_" .. weaponName .. "_Saya", character.Torso, Rig.SHEATH_C0, f, assetModel)
	f.Parent = character
	return f
end

-- Floating stone fists beside the forearms, punching forward. Returns {Right = {welds}, Left = {welds}}.
Rig.FIST_C0 = {Right = CFrame.new(1.6, -0.9, -0.9), Left = CFrame.new(-1.6, -0.9, -0.9)}
function Rig.AttachStoneFists(character)
	local old = character:FindFirstChild("HO_StoneFists")
	if old then old:Destroy() end
	local f = Instance.new("Folder")
	f.Name = "HO_StoneFists"
	local welds = {}
	for _, side in ipairs({"Right", "Left"}) do
		local sub = Instance.new("Folder")
		sub.Name = side
		sub.Parent = f
		attach("HO_Hero_StoneFist_" .. side, character[side .. " Arm"], Rig.FIST_C0[side], sub)
		welds[side] = {}
		for _, d in ipairs(sub:GetDescendants()) do
			if d:IsA("Weld") then table.insert(welds[side], d) end
		end
	end
	f.Parent = character
	return welds
end

Rig.RIGS = RIGS
return Rig
