--[[
	HOLLOW OATH - Capital City Builder  (generated by tools/gen_roblox_builder.py - do not hand-edit)

	HOW TO USE (Roblox Studio, edit mode):
	  1. ServerStorage -> Insert Object -> ModuleScript, rename it  HO_CityBuilder , paste this whole file in.
	  2. View -> Command Bar, run:
	         require(game.ServerStorage.HO_CityBuilder).Build()
	     The city appears in Workspace.HO_City (terrain, streets, stairs, harbour, castle, buildings, trees).
	     Anything not imported yet is a clearly-coloured placeholder.
	  3. Import my FBX files (File -> Import 3D, Scale Unit = Stud) and move each imported Model into
	     ServerStorage.HO_Assets (keep the file names, e.g. HO_Bldg_Machiya_B). Run Build() again:
	     every placeholder with a matching asset is replaced by the real model.
	  4. Optional: upload the texture PNGs, paste their asset ids into TEXTURES below, then run
	         require(game.ServerStorage.HO_CityBuilder).ApplyTextures()

	Plan coordinates: X east 0..900, Y north 0..1200  ->  Roblox X = X - 450, Z = 600 - Y, height = elev.
]]

local Builder = {}

-- Paste uploaded image ids here (rbxassetid://...). Keys are the texture set names from /textures.
local TEXTURES = {
	-- RoofTile_Clay = {Color = "rbxassetid://0", Normal = "rbxassetid://0", Roughness = "rbxassetid://0", Metalness = "rbxassetid://0"},
}

--[[DATA]]

--[[BOUNDS]]

--[[MESHSET]]

local ServerStorage = game:GetService("ServerStorage")
local Lighting = game:GetService("Lighting")
local Terrain = workspace.Terrain

local root, folders
local FACING = { N = 0, W = math.rad(90), S = math.rad(180), E = math.rad(-90) }

local COL = {
	plaster = Color3.fromRGB(232, 226, 212), timber = Color3.fromRGB(58, 42, 32), roof = Color3.fromRGB(70, 78, 90),
	stone = Color3.fromRGB(150, 144, 132), cobble = Color3.fromRGB(128, 122, 112), wood = Color3.fromRGB(132, 104, 74),
	red = Color3.fromRGB(178, 42, 30), pine = Color3.fromRGB(46, 84, 54), bark = Color3.fromRGB(72, 54, 40),
	gold = Color3.fromRGB(214, 170, 76), special = Color3.fromRGB(186, 70, 48), dirt = Color3.fromRGB(150, 126, 96),
}

-- ------------------------------------------------------------------------------------------ helpers
local function W(x, y, e)
	return Vector3.new(x - 450, e or 0, 600 - y)
end

local function part(parent, size, cf, color, material, name, shape)
	local p = Instance.new("Part")
	p.Anchored = true
	p.Size = size
	p.CFrame = cf
	p.Color = color
	p.Material = material or Enum.Material.SmoothPlastic
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	if shape then p.Shape = shape end
	p.Name = name or "Part"
	p.Parent = parent
	return p
end

local function wedge(parent, size, cf, color, name)
	local p = Instance.new("WedgePart")
	p.Anchored = true
	p.Size = size
	p.CFrame = cf
	p.Color = color
	p.Material = Enum.Material.Slate
	p.Name = name or "Wedge"
	p.Parent = parent
	return p
end

local function pointInPoly(x, y, poly)
	local inside = false
	local j = #poly
	for i = 1, #poly do
		local xi, yi = poly[i][1], poly[i][2]
		local xj, yj = poly[j][1], poly[j][2]
		if ((yi > y) ~= (yj > y)) and (x < (xj - xi) * (y - yi) / (yj - yi) + xi) then
			inside = not inside
		end
		j = i
	end
	return inside
end

local function elevAt(x, y)
	local best = 0
	for _, t in ipairs(DATA.tiers) do
		if t.elev > best and pointInPoly(x, y, t.poly) then best = t.elev end
	end
	return best
end

-- vertical scanline fill of a plan polygon with terrain between heights h0..h1
local function fillPoly(poly, h0, h1, material, step)
	step = step or 4
	local xmin, xmax = math.huge, -math.huge
	for _, p in ipairs(poly) do
		xmin = math.min(xmin, p[1]); xmax = math.max(xmax, p[1])
	end
	local x = math.floor(xmin / step) * step
	while x < xmax do
		local xc = x + step / 2
		local ys = {}
		local j = #poly
		for i = 1, #poly do
			local x1, y1 = poly[j][1], poly[j][2]
			local x2, y2 = poly[i][1], poly[i][2]
			if (x1 <= xc and x2 > xc) or (x2 <= xc and x1 > xc) then
				table.insert(ys, y1 + (xc - x1) / (x2 - x1) * (y2 - y1))
			end
			j = i
		end
		table.sort(ys)
		for k = 1, #ys - 1, 2 do
			local ya, yb = ys[k], ys[k + 1]
			if yb - ya > 0.5 then
				local c = W(xc, (ya + yb) / 2, (h0 + h1) / 2)
				Terrain:FillBlock(CFrame.new(c), Vector3.new(step, h1 - h0, yb - ya), material)
			end
		end
		x = x + step
	end
end

-- find an imported asset template by name (anywhere under ServerStorage.HO_Assets)
local function asset(name)
	local lib = ServerStorage:FindFirstChild("HO_Assets")
	if not lib then return nil end
	return lib:FindFirstChild(name, true)
end

-- place a clone so that the asset's own origin (footprint centre / bottom centre) lands on `cf`
local function placeAsset(name, cf, parent)
	local tpl = asset(name)
	if not tpl then return nil end
	local m = tpl:Clone()
	if m:IsA("BasePart") then
		local g = Instance.new("Model"); g.Name = name; m.Parent = g; m = g
	end
	local b = BOUNDS[name]
	local bcf, bsize = m:GetBoundingBox()
	if b then
		-- bbox centre in asset space -> the model's origin in world space (template assumed unrotated)
		local origin = bcf.Position - Vector3.new(b.c[1], b.c[2], b.c[3])
		m.WorldPivot = CFrame.new(origin)
	else
		m.WorldPivot = CFrame.new(bcf.Position - Vector3.new(0, bsize.Y / 2, 0))
	end
	m:PivotTo(cf)
	for _, d in ipairs(m:GetDescendants()) do
		if d:IsA("BasePart") then d.Anchored = true end
	end
	m.Parent = parent
	return m
end

local function label(p, text)
	local bb = Instance.new("BillboardGui")
	bb.Size = UDim2.new(0, 220, 0, 40)
	bb.StudsOffset = Vector3.new(0, p.Size.Y / 2 + 8, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 600
	local t = Instance.new("TextLabel")
	t.Size = UDim2.new(1, 0, 1, 0)
	t.BackgroundTransparency = 0.3
	t.BackgroundColor3 = Color3.fromRGB(20, 26, 38)
	t.TextColor3 = Color3.new(1, 1, 1)
	t.TextScaled = true
	t.Font = Enum.Font.GothamBold
	t.Text = text
	t.Parent = bb
	bb.Parent = p
end

-- simple gable roof from two wedges over a w x d footprint (ridge along local X)
local function placeholderRoof(parent, cf, w, d, rise, overhang)
	overhang = overhang or 2
	local hw = d / 2 + overhang
	local L = w + overhang
	wedge(parent, Vector3.new(L, rise, hw), cf * CFrame.new(0, rise / 2, hw / 2), COL.roof, "RoofFront")
	wedge(parent, Vector3.new(L, rise, hw), cf * CFrame.new(0, rise / 2, -hw / 2) * CFrame.Angles(0, math.pi, 0), COL.roof, "RoofBack")
end

local function roofFor(w, d)
	local opts = {
		{ "HO_Roof_Kirizuma_Small", 12, 12 }, { "HO_Roof_Irimoya_Small", 16, 12 }, { "HO_Roof_Kirizuma_Large", 20, 16 },
		{ "HO_Roof_Irimoya_Medium", 24, 16 }, { "HO_Roof_Irimoya_Large", 32, 24 },
	}
	for _, o in ipairs(opts) do
		if o[2] >= w and o[2] <= w + 4 and o[3] >= d and o[3] <= d + 4 then return o[1] end
	end
	return nil
end

-- generic building: real asset if present, else plinth + plaster block (+ real roof asset if imported)
local function building(parent, name, x, y, elev, w, d, facing, storeys, color, text)
	-- w/d are plan (X/Y) extents; the model's own width runs along its front, so swap for E/W facing
	if facing == "E" or facing == "W" then w, d = d, w end
	local cf = CFrame.new(W(x, y, elev)) * CFrame.Angles(0, FACING[facing] or 0, 0)
	if placeAsset(name, cf, parent) then return end
	local m = Instance.new("Model"); m.Name = name .. "_Placeholder"; m.Parent = parent
	local h = 9 * storeys
	part(m, Vector3.new(w + 0.6, 1, d + 0.6), cf * CFrame.new(0, 0.5, 0), COL.stone, Enum.Material.Slate, "Plinth")
	local body = part(m, Vector3.new(w, h, d), cf * CFrame.new(0, 1 + h / 2, 0), color or COL.plaster, Enum.Material.SmoothPlastic, "Walls")
	for i = 0, storeys do
		part(m, Vector3.new(w + 0.2, 0.7, d + 0.2), cf * CFrame.new(0, 1 + 9 * i - (i == storeys and 0.35 or 0), 0), COL.timber, Enum.Material.Wood, "Beam")
	end
	for _, sx in ipairs({ -1, 1 }) do
		for _, sz in ipairs({ -1, 1 }) do
			part(m, Vector3.new(1.3, h, 1.3), cf * CFrame.new(sx * (w / 2 - 0.5), 1 + h / 2, sz * (d / 2 - 0.5)), COL.timber, Enum.Material.Wood, "Post")
		end
	end
	local top = cf * CFrame.new(0, 1 + h, 0)
	local rname = roofFor(w, d)
	if not (rname and placeAsset(rname, top, m)) then
		placeholderRoof(m, top, w, d, math.max(4, d * 0.35), 2)
	end
	if text then label(body, text) end
	m.PrimaryPart = body
end

-- ------------------------------------------------------------------------------------------ sections
local function buildTerrain()
	Terrain:Clear()
	-- open sea / horizon and sea bed
	Terrain:FillBlock(CFrame.new(W(1150, 600, -16)), Vector3.new(900, 8, 2400), Enum.Material.Sand)
	Terrain:FillBlock(CFrame.new(W(1150, 600, -6)), Vector3.new(900, 12, 2400), Enum.Material.Water)
	fillPoly(DATA.sea, -20, -12, Enum.Material.Sand, 8)
	fillPoly(DATA.sea, -12, 0, Enum.Material.Water, 8)
	-- south edge land skirt (below the town) so the map has no hard edge
	Terrain:FillBlock(CFrame.new(W(386, 20, -6)), Vector3.new(772, 28, 40), Enum.Material.Ground)
	-- tiers: slate body (reads as fitted stone retaining walls on the sides) + top layer
	for _, t in ipairs(DATA.tiers) do
		local top = (t.elev >= 46) and Enum.Material.Grass or Enum.Material.Ground
		fillPoly(t.poly, -20, t.elev - 2, Enum.Material.Slate, 4)
		fillPoly(t.poly, t.elev - 2, t.elev, top, 4)
	end
	-- cliffs and mountain behind the castle
	for i, c in ipairs(DATA.cliffs) do
		fillPoly(c, -20, (i == 3) and 50 or 130, Enum.Material.Rock, 4)
	end
	Terrain:FillBlock(CFrame.new(W(450, 1300, 60)), Vector3.new(1400, 160, 200), Enum.Material.Rock)
	-- tidal canal cut into the lower town
	fillPoly(DATA.inlet, -2, 20, Enum.Material.Air, 4)
	fillPoly(DATA.inlet, -12, 0, Enum.Material.Water, 4)
	for _, r in ipairs(DATA.rocks) do
		Terrain:FillBall(W(r.c[1], r.c[2], 2), r.r * 0.8, Enum.Material.Rock)
		Terrain:FillBall(W(r.c[1], r.c[2], -8), r.r, Enum.Material.Rock)
	end
end

local function buildStreets()
	local f = folders.Streets
	for _, s in ipairs(DATA.streets) do
		local mat = (s.kind == "alley") and Enum.Material.Ground or Enum.Material.Cobblestone
		local col = (s.kind == "alley") and COL.dirt or COL.cobble
		for i = 1, #s.path - 1 do
			local a, b = s.path[i], s.path[i + 1]
			local dx, dy = b[1] - a[1], b[2] - a[2]
			local len = math.sqrt(dx * dx + dy * dy)
			local n = math.max(1, math.floor(len / 8 + 0.5))
			for k = 0, n - 1 do
				local t0, t1 = k / n, (k + 1) / n
				local x0, y0 = a[1] + dx * t0, a[2] + dy * t0
				local x1, y1 = a[1] + dx * t1, a[2] + dy * t1
				local xc, yc = (x0 + x1) / 2, (y0 + y1) / 2
				local e = elevAt(xc, yc)
				local p0, p1 = W(x0, y0, e + 0.1), W(x1, y1, e + 0.1)
				local cf = CFrame.lookAt((p0 + p1) / 2, p1)
				part(f, Vector3.new(s.width, 0.2, (p1 - p0).Magnitude + 0.05), cf, col, mat, "Street")
			end
		end
	end
	-- market square paving
	part(f, Vector3.new(84, 0.25, 72), CFrame.new(W(440, 400, 20.12)), Color3.fromRGB(150, 142, 128), Enum.Material.Cobblestone, "MarketSquare")
end

local function buildStairs()
	local f = folders.Streets
	for _, s in ipairs(DATA.stairs) do
		local lo, hi = string.match(s.rise, "(%d+)%D+(%d+)")
		lo, hi = tonumber(lo), tonumber(hi)
		if lo > hi then lo, hi = hi, lo end
		local alongX = s.size[1] >= s.size[2]
		local len = alongX and s.size[1] or s.size[2]
		local wid = alongX and s.size[2] or s.size[1]
		local cx, cy = s.c[1], s.c[2]
		-- which end is high?
		local ax, ay = alongX and 1 or 0, alongX and 0 or 1
		local eA = elevAt(cx - ax * (len / 2 + 6), cy - ay * (len / 2 + 6))
		local eB = elevAt(cx + ax * (len / 2 + 6), cy + ay * (len / 2 + 6))
		local dir = (eB >= eA) and 1 or -1
		local n = math.max(2, hi - lo)
		local depth = len / n
		for k = 1, n do
			local top = lo + (hi - lo) * k / n
			local off = (-len / 2 + depth * (k - 0.5)) * dir
			local px, py = cx + ax * off, cy + ay * off
			local size = alongX and Vector3.new(depth, top - lo + 2, wid) or Vector3.new(wid, top - lo + 2, depth)
			part(f, size, CFrame.new(W(px, py, (top + lo - 2) / 2)), COL.stone, Enum.Material.Slate, "Step")
		end
	end
end

local function buildCastleWalls()
	local f = folders.Castle
	local gates = DATA.gates
	for _, t in ipairs(DATA.tiers) do
		if t.elev >= 46 then
			local poly = t.poly
			for i = 1, #poly do
				local a, b = poly[i], poly[(i % #poly) + 1]
				local dx, dy = b[1] - a[1], b[2] - a[2]
				local len = math.sqrt(dx * dx + dy * dy)
				local n = math.max(1, math.floor(len / 12))
				for k = 0, n - 1 do
					local x0, y0 = a[1] + dx * k / n, a[2] + dy * k / n
					local x1, y1 = a[1] + dx * (k + 1) / n, a[2] + dy * (k + 1) / n
					local xc, yc = (x0 + x1) / 2, (y0 + y1) / 2
					local nearGate = false
					for _, g in ipairs(gates) do
						if math.abs(g.c[1] - xc) < 16 and math.abs(g.c[2] - yc) < 10 then nearGate = true end
					end
					if not nearGate then
						local p0, p1 = W(x0, y0, t.elev), W(x1, y1, t.elev)
						local cf = CFrame.lookAt((p0 + p1) / 2, p1)
						local L = (p1 - p0).Magnitude + 0.6
						part(f, Vector3.new(2, 6, L), cf * CFrame.new(0, 3, 0), COL.plaster, Enum.Material.SmoothPlastic, "CastleWall")
						part(f, Vector3.new(3, 0.8, L + 0.4), cf * CFrame.new(0, 6.4, 0), COL.roof, Enum.Material.Slate, "WallCap")
					end
				end
			end
		end
	end
	for _, g in ipairs(DATA.gates) do
		local e = elevAt(g.c[1], g.c[2] + 8)
		building(folders.Castle, "HO_Castle_Gatehouse", g.c[1], g.c[2], e, 28, 12, "S", 1, COL.timber, g.label)
	end
	for _, y in ipairs(DATA.yagura) do
		local e = elevAt(y[1] + 0.1, y[2] + 0.1)
		for _, t in ipairs(DATA.tiers) do
			if t.elev >= 46 and pointInPoly(y[1] + 2, y[2] + 2, t.poly) then e = math.max(e, t.elev) end
		end
		building(folders.Castle, "HO_Castle_Yagura", y[1], y[2], e, 16, 12, "S", 2, COL.plaster, nil)
	end
end

local function buildKeep(k)
	local f = folders.Castle
	local cf = CFrame.new(W(k.c[1], k.c[2], k.elev)) * CFrame.Angles(0, FACING[k.facing], 0)
	if placeAsset("HO_Castle_Keep", cf, f) then return end
	local m = Instance.new("Model"); m.Name = "HO_Castle_Keep_Placeholder"; m.Parent = f
	local w, d = k.size[1], k.size[2]
	-- battered stone base
	local base = part(m, Vector3.new(w, 16, d), cf * CFrame.new(0, 8, 0), COL.stone, Enum.Material.Slate, "StoneBase")
	local y = 16
	for i = 1, 5 do
		local s = 1 - (i - 1) * 0.16
		local tw, td = w * 0.82 * s, d * 0.82 * s
		part(m, Vector3.new(tw, 9, td), cf * CFrame.new(0, y + 4.5, 0), COL.plaster, Enum.Material.SmoothPlastic, "Tier" .. i)
		part(m, Vector3.new(tw + 5, 1.2, td + 5), cf * CFrame.new(0, y + 9.2, 0), COL.roof, Enum.Material.Slate, "Skirt" .. i)
		y = y + 10
	end
	placeholderRoof(m, cf * CFrame.new(0, y, 0), w * 0.82 * 0.36, d * 0.82 * 0.36, 7, 3)
	for _, sx in ipairs({ -1, 1 }) do
		part(m, Vector3.new(1.2, 3, 2.5), cf * CFrame.new(sx * (w * 0.15 + 1), y + 7.5, 0), COL.gold, Enum.Material.Metal, "Shachihoko")
	end
	label(base, k.label)
end

local function buildKey()
	for _, k in ipairs(DATA.key) do
		if k.id == "keep" then
			buildKeep(k)
		elseif k.kind == "yard" then
			part(folders.Castle, Vector3.new(k.size[1], 0.3, k.size[2]), CFrame.new(W(k.c[1], k.c[2], k.elev + 0.15)),
				Color3.fromRGB(200, 184, 150), Enum.Material.Sand, "TrainingYard")
		elseif k.kind ~= "square" and k.id ~= "lighthouse" then
			local names = { tidewatch_inn = "HO_Bldg_TidewatchInn", blacksmith = "HO_Bldg_Blacksmith", armory = "HO_Bldg_Armory",
				general_store = "HO_Bldg_GeneralStore", magic_stall = "HO_Bldg_MagicStall", academy_hall = "HO_Castle_AcademyHall" }
			local storeys = (k.id == "magic_stall") and 1 or 2
			local col = (k.kind == "special") and COL.special or COL.plaster
			building(folders.Buildings, names[k.id] or ("HO_Bldg_" .. k.id), k.c[1], k.c[2], k.elev, k.size[1], k.size[2],
				k.facing ~= "-" and k.facing or "S", storeys, col, k.label)
		end
	end
end

local function buildTown()
	for _, l in ipairs(DATA.lots) do
		local name = l.asset
		if l.d <= 12 then name = "HO_Bldg_Machiya_A" end
		building(folders.Buildings, name, l.x, l.y, l.elev, l.w, math.min(l.d, (name == "HO_Bldg_Machiya_A") and 12 or 20),
			l.facing, (name == "HO_Bldg_Machiya_A") and 1 or 2, COL.plaster, nil)
	end
	for _, k in ipairs(DATA.kura) do
		building(folders.Buildings, "HO_Bldg_Kura", k[1], k[2], elevAt(k[1], k[2]), 24, 20, "E", 2, COL.plaster, nil)
	end
end

local function buildHarbour()
	local f = folders.Harbour
	for _, p in ipairs(DATA.piers) do
		local cf0 = CFrame.new(W(p.x0 + p.length / 2, p.y, 4))
		if not placeAsset("HO_Harbour_Pier", CFrame.new(W(p.x0, p.y, 0)) * CFrame.Angles(0, FACING.E, 0), f) then
			part(f, Vector3.new(p.length, 0.6, p.width), cf0 * CFrame.new(0, -0.3, 0), COL.wood, Enum.Material.WoodPlanks, p.label)
			part(f, Vector3.new(16, 0.6, p.width + 16), CFrame.new(W(p.x0 + p.length - 8, p.y, 3.7)), COL.wood, Enum.Material.WoodPlanks, "PierHead")
			for x = p.x0 + 4, p.x0 + p.length, 8 do
				for _, s in ipairs({ -1, 1 }) do
					part(f, Vector3.new(1, 1, 16), CFrame.new(W(x, p.y + s * (p.width / 2 - 0.5), -4)) * CFrame.Angles(math.rad(90), 0, 0),
						COL.timber, Enum.Material.Wood, "Post", Enum.PartType.Cylinder)
				end
			end
		end
	end
	-- promenade paving + quay edge
	part(f, Vector3.new(40, 0.2, 740), CFrame.new(W(752, 410, 4.1)), COL.cobble, Enum.Material.Cobblestone, "Promenade")
	part(f, Vector3.new(2, 1, 780), CFrame.new(W(771, 430, 4.5)), COL.stone, Enum.Material.Slate, "QuayCap")
	-- arched bridge over the canal
	local b = DATA.bridge
	if not placeAsset("HO_Harbour_ArchBridge", CFrame.new(W(b.c[1], b.c[2], 4)), f) then
		local n = 12
		for i = 0, n - 1 do
			local t0, t1 = i / n, (i + 1) / n
			local y0 = b.c[2] - b.size[2] / 2 + b.size[2] * t0
			local y1 = b.c[2] - b.size[2] / 2 + b.size[2] * t1
			local z0 = 4 + 6 * math.sin(math.pi * t0)
			local z1 = 4 + 6 * math.sin(math.pi * t1)
			local p0, p1 = W(b.c[1], y0, z0), W(b.c[1], y1, z1)
			local cf = CFrame.lookAt((p0 + p1) / 2, p1)
			part(f, Vector3.new(b.size[1], 0.8, (p1 - p0).Magnitude + 0.1), cf, COL.wood, Enum.Material.WoodPlanks, "BridgeDeck")
			for _, s in ipairs({ -1, 1 }) do
				part(f, Vector3.new(0.5, 0.4, (p1 - p0).Magnitude + 0.1), cf * CFrame.new(s * (b.size[1] / 2 - 0.3), 3.2, 0), COL.red, Enum.Material.SmoothPlastic, "Rail")
				part(f, Vector3.new(0.4, 3, 0.4), cf * CFrame.new(s * (b.size[1] / 2 - 0.3), 1.6, 0), COL.red, Enum.Material.SmoothPlastic, "Baluster")
			end
		end
	end
	-- causeway to the lighthouse rock
	for i = 1, #DATA.causeway - 1 do
		local a, c = DATA.causeway[i], DATA.causeway[i + 1]
		local p0, p1 = W(a[1], a[2], 3), W(c[1], c[2], 3)
		part(f, Vector3.new(12, 6, (p1 - p0).Magnitude + 6), CFrame.lookAt((p0 + p1) / 2, p1) * CFrame.new(0, -2, 0), COL.stone, Enum.Material.Slate, "Causeway")
	end
	-- lighthouse
	local lh = W(856, 904, 12)
	if not placeAsset("HO_Harbour_Lighthouse", CFrame.new(lh), f) then
		part(f, Vector3.new(28, 12, 12), CFrame.new(lh + Vector3.new(0, 14, 0)) * CFrame.Angles(0, 0, math.rad(90)), COL.plaster, Enum.Material.SmoothPlastic, "Tower", Enum.PartType.Cylinder)
		local lamp = part(f, Vector3.new(6, 8, 8), CFrame.new(lh + Vector3.new(0, 31, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color3.fromRGB(255, 214, 140), Enum.Material.Neon, "Lantern", Enum.PartType.Cylinder)
		local pl = Instance.new("PointLight"); pl.Range = 60; pl.Brightness = 3; pl.Color = Color3.fromRGB(255, 200, 120); pl.Parent = lamp
		wedge(f, Vector3.new(12, 5, 6), CFrame.new(lh + Vector3.new(0, 37.5, 3)), COL.roof, "Roof")
		wedge(f, Vector3.new(12, 5, 6), CFrame.new(lh + Vector3.new(0, 37.5, -3)) * CFrame.Angles(0, math.pi, 0), COL.roof, "Roof")
	end
end

local function torii(parent, x, y, facing)
	local e = elevAt(x, y)
	local cf = CFrame.new(W(x, y, e)) * CFrame.Angles(0, (facing == "E" or facing == "W") and math.rad(90) or 0, 0)
	if placeAsset("HO_Prop_Torii", cf, parent) then return end
	local m = Instance.new("Model"); m.Name = "Torii_Placeholder"; m.Parent = parent
	for _, s in ipairs({ -1, 1 }) do
		part(m, Vector3.new(11, 1.3, 1.3), cf * CFrame.new(s * 4.5, 5.5, 0) * CFrame.Angles(0, 0, math.rad(90)), COL.red, Enum.Material.SmoothPlastic, "Pillar", Enum.PartType.Cylinder)
	end
	part(m, Vector3.new(14, 1, 1.6), cf * CFrame.new(0, 11.3, 0), Color3.fromRGB(30, 26, 24), Enum.Material.SmoothPlastic, "Kasagi")
	part(m, Vector3.new(13, 0.8, 1.3), cf * CFrame.new(0, 10.5, 0), COL.red, Enum.Material.SmoothPlastic, "Shimaki")
	part(m, Vector3.new(11.5, 0.7, 0.8), cf * CFrame.new(0, 8.8, 0), COL.red, Enum.Material.SmoothPlastic, "Nuki")
end

local function buildProps()
	for _, t in ipairs(DATA.torii) do torii(folders.Props, t.c[1], t.c[2], t.facing) end
	for _, wl in ipairs(DATA.wells) do
		local p = W(wl[1], wl[2], elevAt(wl[1], wl[2]))
		if not placeAsset("HO_Prop_Well", CFrame.new(p), folders.Props) then
			part(folders.Props, Vector3.new(2.5, 5, 5), CFrame.new(p + Vector3.new(0, 1.25, 0)) * CFrame.Angles(0, 0, math.rad(90)), COL.stone, Enum.Material.Slate, "Well", Enum.PartType.Cylinder)
		end
	end
end

local function buildTrees()
	local f = folders.Nature
	local S = { S = 0.7, M = 1.0, L = 1.4 }
	for i, t in ipairs(DATA.trees) do
		local e = elevAt(t.x, t.y)
		local p = W(t.x, t.y, e)
		local rot = CFrame.Angles(0, (i * 2.399) % (2 * math.pi), 0)
		if not placeAsset("HO_Tree_Pine_" .. t.size, CFrame.new(p) * rot, f) then
			local s = S[t.size] or 1
			local m = Instance.new("Model"); m.Name = "Pine_Placeholder"; m.Parent = f
			part(m, Vector3.new(10 * s, 1.2 * s, 1.2 * s), CFrame.new(p + Vector3.new(0, 5 * s, 0)) * CFrame.Angles(0, 0, math.rad(90)), COL.bark, Enum.Material.Wood, "Trunk", Enum.PartType.Cylinder)
			for k, h in ipairs({ 6, 8.5, 10.5 }) do
				local r = (9 - k * 2) * s
				part(m, Vector3.new(2.2 * s, r, r), CFrame.new(p + Vector3.new((k - 2) * 1.2 * s, h * s, 0)) * rot * CFrame.Angles(0, 0, math.rad(90)),
					COL.pine, Enum.Material.Grass, "Foliage", Enum.PartType.Cylinder)
			end
		end
	end
end

local function setupLighting()
	Lighting.Technology = Enum.Technology.Future
	Lighting.ClockTime = 17.4
	Lighting.GeographicLatitude = 35
	Lighting.Brightness = 2.2
	Lighting.Ambient = Color3.fromRGB(70, 58, 52)
	Lighting.OutdoorAmbient = Color3.fromRGB(120, 104, 96)
	Lighting.EnvironmentDiffuseScale = 1
	Lighting.EnvironmentSpecularScale = 1
	local function ensure(class, name)
		local o = Lighting:FindFirstChild(name) or Instance.new(class)
		o.Name = name; o.Parent = Lighting
		return o
	end
	local atm = ensure("Atmosphere", "HO_Atmosphere")
	atm.Density = 0.32; atm.Offset = 0.1; atm.Color = Color3.fromRGB(255, 196, 150); atm.Decay = Color3.fromRGB(110, 120, 150)
	atm.Glare = 0.4; atm.Haze = 1.6
	local bloom = ensure("BloomEffect", "HO_Bloom"); bloom.Intensity = 0.4; bloom.Size = 30; bloom.Threshold = 1.2
	local rays = ensure("SunRaysEffect", "HO_SunRays"); rays.Intensity = 0.06; rays.Spread = 0.6
	local cc = ensure("ColorCorrectionEffect", "HO_ColorCorrection"); cc.Contrast = 0.08; cc.Saturation = 0.08
	cc.TintColor = Color3.fromRGB(255, 244, 232)
end

-- ------------------------------------------------------------------------------------------ public API
function Builder.Build(opts)
	opts = opts or {}
	local t0 = os.clock()
	local old = workspace:FindFirstChild("HO_City")
	if old then old:Destroy() end
	root = Instance.new("Folder"); root.Name = "HO_City"; root.Parent = workspace
	folders = {}
	for _, n in ipairs({ "Streets", "Buildings", "Castle", "Harbour", "Props", "Nature" }) do
		local fo = Instance.new("Folder"); fo.Name = n; fo.Parent = root; folders[n] = fo
	end
	if opts.terrain ~= false then buildTerrain() end
	buildStreets(); buildStairs()
	buildCastleWalls(); buildKey(); buildTown()
	buildHarbour(); buildProps()
	if opts.trees ~= false then buildTrees() end
	setupLighting()
	local n = 0
	for _, d in ipairs(root:GetDescendants()) do if d:IsA("BasePart") then n = n + 1 end end
	print(string.format("[HO_CityBuilder] built in %.1fs, %d parts. Placeholders are replaced by assets in ServerStorage.HO_Assets.", os.clock() - t0, n))
	return root
end

-- Gives every imported MeshPart its ONE SurfaceAppearance. The texture set comes from the part name
-- ("<Object>__<Set>") or, for single-material parts, from MESH_SET (generated from the manifest).
-- Source: ReplicatedStorage.HO_Materials.<Set> (a SurfaceAppearance template) if present, else TEXTURES ids.
function Builder.ApplyTextures(root)
	root = root or ServerStorage:FindFirstChild("HO_Assets")
	if not root then warn("No ServerStorage.HO_Assets folder"); return end
	local lib = game:GetService("ReplicatedStorage"):FindFirstChild("HO_Materials")
	local count, missing = 0, {}
	for _, d in ipairs(root:GetDescendants()) do
		if d:IsA("MeshPart") then
			local set = string.match(d.Name, "__([%w_]+)$") or MESH_SET[d.Name]
			local old = d:FindFirstChildOfClass("SurfaceAppearance")
			if set then
				local sa
				if lib and lib:FindFirstChild(set) then
					sa = lib[set]:Clone()
				elseif TEXTURES[set] then
					local ids = TEXTURES[set]
					sa = Instance.new("SurfaceAppearance")
					sa.ColorMap = ids.Color or ""; sa.NormalMap = ids.Normal or ""
					sa.RoughnessMap = ids.Roughness or ""; sa.MetalnessMap = ids.Metalness or ""
				end
				if sa then
					if old then old:Destroy() end
					sa.Name = set
					sa.Parent = d
					count = count + 1
				else
					missing[set] = true
				end
			else
				missing["(unknown set for " .. d.Name .. ")"] = true
			end
		end
	end
	print("[HO_CityBuilder] SurfaceAppearances applied:", count)
	for k in pairs(missing) do warn("[HO_CityBuilder] no texture source for", k) end
end

-- Parts that belong together (e.g. a sliding door split into Door1__Timber_Light + Door1__Shoji_Paper)
-- share the name before "__". Returns {baseName = {parts}} for a model, handy for door/glow scripts.
function Builder.GroupParts(model)
	local groups = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			local base = string.match(d.Name, "^(.-)__[%w_]+$") or d.Name
			groups[base] = groups[base] or {}
			table.insert(groups[base], d)
		end
	end
	return groups
end

return Builder
